Miles/ora 1377 protect validators from egregious data
allora-network/allora-chain pull request #231
Opened 2024-05-09 17:46 UTC by br4e

2024-05-11 18:07 UTC, kpeluso requested changes
Kinda wish you had kept `extra_data`. Idea was to maximize backward compatibility later when subtopics better supported. Not big prio to maintain tho.

More importantly you need to need to remember to follow the checklist here when adding new global params:
https://www.notion.so/upshothq/Adding-New-Global-Parameters-Checklist-6216783e3b4f4280a2fda6f3487f0164

2024-05-11 18:07 UTC, kpeluso commented on x/emissions/keeper/msgserver/msg_server_losses.go
> +	serializedMsg, err := proto.Marshal(msg)
same

2024-05-13 16:48 UTC, br4e commented on x/emissions/keeper/msgserver/msg_server_worker_payload.go
> +	serializedMsg, err := proto.Marshal(msg)
yeah I was trying to do that but I couldn't figure out how to get the function argument type to be generic enough. I figured out how to do it though and updated

2024-05-13 17:51 UTC, br4e commented
I can keep the extraData if you want. Since that field now introduces a security risk, I thought it would be better to add it later if we need it in an upgrade. Upgrades are costly, but I suspect we will be doing a lot of them at the beginning. 

As for the checklist: 

https://www.notion.so/upshothq/Adding-New-Global-Parameters-Checklist-6216783e3b4f4280a2fda6f3487f0164?pvs=4

`x/emissions/proto/emissions/v1/types.proto` doesn't seem to be used for parameters as far as I can tell, so I didn't update there

2024-05-13 18:04 UTC, kpeluso approved these changes

2024-05-13 18:04 UTC, merged