Prevent calling RemoveStake/RemoveDelegateStake with negative amount
allora-network/allora-chain pull request #441
Opened 2024-07-19 18:58 UTC by relyt29

## What is the purpose of the change

This PR fixes a critical-severity issue that would allow any random person on the internet to denial of service the Allora chain, by sending a negative Coin amount to the RemoveDelegateStake function. The fix merely checks that the value is positive, thereby preventing an eventual panic and halt of the chain.

## Testing and Verifying

This change added tests that check that you cannot try to RemoveStake of negative amounts of coins.

## Documentation and Release Note

This PR has no implications on documentation.

2024-07-19 18:59 UTC, relyt29 commented
Closes ORA-1928

2024-07-20 12:29 UTC, guilherme-brandao requested changes

2024-07-20 12:29 UTC, guilherme-brandao commented on x/emissions/keeper/msgserver/msg_server_stake.go
> +	}
could be just one line

2024-07-20 12:29 UTC, guilherme-brandao commented on x/emissions/keeper/msgserver/msg_server_stake.go
> +	}
same

2024-07-20 12:30 UTC, guilherme-brandao approved these changes
approving but check comment plz

2024-07-20 17:27 UTC, merged