log abci method durations
allora-network/allora-chain pull request #669
Opened 2024-11-12 23:08 UTC by spooktheducks

## Purpose of Changes and their Description

## Link(s) to Ticket(s) or Issue(s) resolved by this PR

## Are these changes tested and documented?

- [ ] If tested, please describe how. If not, why tests are not needed.
- [ ] If documented, please describe where. If not, describe why docs are not needed.
- [ ] Added to `Unreleased` section of `CHANGELOG.md`?

## Still Left Todo

*Fill this out if this is a Draft PR so others can help.*

2024-11-12 23:19 UTC, kpeluso approved these changes, later dismissed

2024-11-13 00:04 UTC, relyt29 approved these changes, later dismissed

2024-11-13 09:22 UTC, amimart approved these changes, later dismissed

2024-11-14 15:31 UTC, guilherme-brandao requested changes
I'd turn this into `Debug` instead of `Info`.

2024-11-25 19:11 UTC, fernandofcampos submitted a review, later dismissed

2024-11-25 20:07 UTC, guilherme-brandao approved these changes

2024-11-25 20:08 UTC, kpeluso approved these changes

2024-11-25 20:18 UTC, amimart approved these changes

2024-11-25 20:25 UTC, merged